### ISSUE TITLE
Can it support customize arguments info?

### ISSUE THREAD

**Issue by elvis-macak** [google/python-fire#10]
Like can I customize the argument type, description or something else?

I would like to export it as a json schema file , and build it as a gui tool with the export schema file.

Thx

**Comment by ftyyy** [comment]
https://m.facebook.com/photo.php?fbid=177436512606927&id=100010217385780&set=a.142689369414975.1073741828.100010217385780&source=11#

**Comment by dbieber** [comment]
- You can specify the description by adding docstrings to your code. e.g. if you are calling Fire on a function, the function's docstring will be used in the help message of the resulting CLI.
- By default, the argument type is inferred from the argument itself, not from the function being called. There is an experimental feature that lets you change the way arguments are parsed (see decorators.py), but it's just experimental.
- Exporting a description of the CLI as json and using that for other projects, like making GUI tools, is an interesting idea. It's definitely doable, but is non-trivial, and also not a priority. If you're interested in pursuing this route, I recommend looking at how completion scripts are generated in completion.py. You may be able to do something similar to export the information that you're interested in.
