### ISSUE TITLE
Completion script generation

### ISSUE THREAD

**Issue by edmBernard** [google/python-fire#101]
Since the script name getter method have been change [here](https://github.com/google/python-fire/blame/d9982003c6c9a1b6fb3add26d26f6eaf1e007332/fire/core.py#L104) du to this issue https://github.com/google/python-fire/issues/51
from `name = name or sys.argv[0]` to `name = name or os.path.basename(sys.argv[0])` 
The completion script don't work anymore on linux: `./myscript.py` is replaced by `myscript.py`

**Comment by may55** [comment]
I am new to open source, can I get some help to fix this issue?

**Comment by edmBernard** [comment]
I don't find better idea to just add the executable name in fire arguments for linux it will be :
```
fire.Fire(name='./cipher.py')
```
