### ISSUE TITLE
Cut a new release for python-fire

### ISSUE THREAD

**Issue by jtratner** [google/python-fire#112]
Hi @dbieber - would you be able to cut a new release for python-fire?  I'd really love to be able to use that parsing fix! :)

Also: if there's any way I can help speed that process up, please tell me!

**Comment by dbieber** [comment]
What's the parsing fix your interested in?

**Comment by jtratner** [comment]
Yeah #99 - brought it up here - https://github.com/google/python-fire/issues/109 - and then closed the issue because already fixed in master heh

**Comment by dbieber** [comment]
Got it. Sure, I will cut a new release by mid-February at the latest, possibly sooner.

**Comment by jtratner** [comment]
Hi @dbieber - any update here? :)

**Comment by dbieber** [comment]
Today!

**Comment by jtratner** [comment]
Hurray! :)

**Comment by dbieber** [comment]
v0.1.3 is now available from [PyPi](https://pypi.python.org/pypi/fire).
Release notes [here](https://github.com/google/python-fire/releases/tag/v0.1.3).

**Comment by jtratner** [comment]
Thanks @dbieber! :)
