### ISSUE TITLE
Chaining function calls

### ISSUE THREAD

**Issue by khavishbhundoo** [google/python-fire#115]
I would want to call  my command line app as follows:

AsyncDownloader.py set-source-csv urls.csv urls set_destination_path ./images download

I have already made the methods return self.My code is [here](https://pastebin.com/iq3S0Ljb)

**Comment by dbieber** [comment]
At a glance, what you're doing looks right to me.
What is the problem you're running into?

**Comment by khavishbhundoo** [comment]
Thats why i closed the issue....i misread the output

**Comment by dbieber** [comment]
Oh, great :)
