### ISSUE TITLE
Permission to generate stubs for python-fire in typeshed

### ISSUE THREAD

**Issue by waseem18** [google/python-fire#123]
Hi Folks,

I would like to add stubs for _python-fire_ to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the Python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner(s) before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

These stubs will be used by mypy and Pycharm. I'll start working on creating stubs after I get permission from the owners or maintainers of _python-fire_.

Thank You.

**Comment by dbieber** [comment]
Permission granted. Thank you for checking in! 👍

**Comment by dbieber** [comment]
Please keep us posted as to what comes of this

**Comment by JulesGM** [comment]
@waseem18 did you end up doing it?

**Comment by boompig** [comment]
Did python-fire ever get type stubs?
