### ISSUE TITLE
Version number as package attribute

### ISSUE THREAD

**Issue by keithpenney** [google/python-fire#124]
Is there a more direct way to expose the version number to the user?  Perhaps a `__version__` package attribute?  I dropped these two lines into the `/fire/__init__.py` file and it works fine for 2.7.6 and 3.6.4.

```python
import  pkg_resources
__version__ = pkg_resources.get_distribution('fire').version
```
It's not the most elegant solution.  [Other ideas.](https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version)

**Comment by dbieber** [comment]
Done in 585d4724412796601a27475c56e35660636bb5e2
