### ISSUE TITLE
error: Could not consume arg 

### ISSUE THREAD

**Issue by orangeSi** [google/python-fire#126]
Hi~
   This is my code:
```
import fire
class caluater():
    def __init__(self):
        print ("start caluate")
        self.A = 2
    def add(self, num):
        self.A = self.A + num
        print (f"add {num}")
    def multip(self, nump):
        self.A = self.A * nump
        print (f"multiply {nump}")
    def final(self):
        return ("final, A is "+str(self.A))

if __name__ == "__main__":
    fire.Fire(caluater)
```

but when I run `python test.py add 3  multip 5 final`, get this error:
```
start caluate
add 3
Fire trace:
1. Initial component
2. Instantiated class "caluater" (/ifswh1/BC_PS/sikaiwei/bin/python3/lib/fire.test.py:4)
3. Accessed property "add" (/ifswh1/BC_PS/sikaiwei/bin/python3/lib/fire.test.py:8)
4. Called routine "add" (/ifswh1/BC_PS/sikaiwei/bin/python3/lib/fire.test.py:8)
5. ('Could not consume arg:', 'multip')

Type:        NoneType
String form: None

Usage:       fire.test.py add 3 
```

**Comment by GeorgHeesch** [comment]
Hi, 

after "add 3" the following elements of the command line will be applied as if you had called
`fire.Fire(calculator.add(3))`
so to get the desired behaviour change `add()` and `multip()` to return `self`.

**Comment by orangeSi** [comment]
I change to this, then it works ! but I don't knwo why must to call return  for every function of class.
```
class caluater():
    def __init__(self):
        """
        for test
        python /ifswh1/BC_PS/sikaiwei/bin/python3/lib/fire.test.py add 3  multip 5 final

        """
        self.A = 2
        print (f"start caluate, A is {self.A}")
    def add(self, num):
        self.A = self.A + num
        print (f"add {num}")
        return self
    def multip(self, nump):
        self.A = self.A * nump
        print (f"multiply {nump}")
        return self
    def final(self):
         print ("final, A is "+str(self.A))

if __name__ == "__main__":
    fire.Fire(caluater)
```

**Comment by dbieber** [comment]
Thanks @GeorgHeesch for answering @orangeSi's question!

The reason you need to "return self" for each function is that each of the functions in your command (`add 3`, `multip 5`, and `final`) are called on the result of the previous function. `add 3` is called on the result of instantiating the class; `multip 5` is called on the value returned by `add`; `final` is called on the value returned by `multip 5`. If you don't return anything, then Fire doesn't know what to call `multip 5` on.
