### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by 1oglop1** [google/python-fire#129]
Hi, thank you for amazing project it helped me a lot already.

However I'm running in an issue when argument has a default value of `None`

when I have function like this:
```
 def restore_snapshot(self, repository, snapshot, body=None, params=None):
        response = self.es_client.snapshot.restore(repository, snapshot, body=body, params=params)
        print(response.status_code)
        print(response.text)
```
and I run it

`python .\es-scripts.py --host=$es_test restore-snapshot --repository=$snapsho
t_repo --snapshot="es-manual-snapshot"`
then I get this error
```
self.es_client.snapshot.restore(repository, snapshot, body=body, params=params)
  File "D:\Users\jgazda\.virtualenvs\es-1RO09quw\lib\site-packages\elasticsearch\client\utils.py", line 65, in _wrapped
    params = kwargs.pop('params').copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

I'd like to know if am I doing something wrong or this is a bug / indented behaviour and if there is an workaround?

**Comment by dbieber** [comment]
Hi, I think this is an issue with how you're using elasticsearch, not an issue with Python Fire.
From the error message you posted, it looks like the snapshot.restore function in elasticsearch doesn't accept None as a value for "params". It expects a dict for params. To resolve this, change your function like so:

```
def restore_snapshot(self, repository, snapshot, body=None, params=None):
  params = params or {}
  response = self.es_client.snapshot.restore(repository, snapshot, body=body, params=params)
  print(response.status_code)
  print(response.text)
```
