### ISSUE TITLE
Issue when no entry point is defined

### ISSUE THREAD

**Issue by ansdma** [google/python-fire#133]
I have this code:
```
import fire

class Calculator(object):

  def add(self, x, y):
    return x + y

  def multiply(self, x, y):
    return x * y

if __name__ == '__main__':
  fire.Fire()

```

When I run `python file.py -- --help` I get:
```
Type:        dict
String form: {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x10a19ce10>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': 'file.py', '__cached__': None, 'fire': <module 'fire' from '/Users/a/.pyenv/versions/.../python3.6/site-packages/fire/__init__.py'>, 'Calculator': <class '__main__.Calculator'>}
Length:      11

Usage:       file.py 
             file.py fire
             file.py Calculator

```

Is this expected behavior?

Best

**Comment by dbieber** [comment]
Yes, that is the current expected behavior. I'm aware it has much room for improvement. We have an ongoing (but only slowly getting off the ground) effort to improve these help screens. Tracking this in #121.

**Comment by dbieber** [comment]
Oh, I guess I should explain:

When you call `fire.Fire()` with no arguments, it's as if you had called `fire.Fire(locals_and_globals)` where locals_and_globals is the merge of the two dicts, locals() and globals().
