### ISSUE TITLE
Feature Request: call arbitrary function in a project by simply add fire in __main__.py

### ISSUE THREAD

**Issue by traveller59** [google/python-fire#137]
# Problem
If we want to call a function in a submodule of a project, we may need to replace existed __main__ function with fire.Fire(). every file which needs to add fire call need to do same things.

# Possible Implementation
We can just add a simple line fire.Fire('.') in \_\_main\_\_.py or other file. When we use following commands:
```bash
python -m project project.submodule1.add 1 2
python -m project .submodule1.add 1 2
python -m project submodule1.add 1 2
python main.py .submodule1.add 1 2
```
The fire object will find and import target file, analysis function/object signature and call it.

**Comment by dbieber** [comment]
Starting in 0.3.0 you'll be able to run `python -m fire project.submodule.add 1 2` even without needing to import fire in project or in submodule. It's not exactly what you're requesting, but maybe solves the same underlying problem.
