### ISSUE TITLE
pass the parameters，it shows the "inf"

### ISSUE THREAD

**Issue by diaojunxian** [google/python-fire#138]
As the code is very simple, like this
```
import fire


def test(current):
    print current

    
if __name__ == '__main__':
    fire.Fire(test)
```
if I pass the parameter like this,`python test_fire.py --current=297e7814231`,it print `inf`，but，when I pass the other parameters，it shows good.

why it happend?

**Comment by dbieber** [comment]
297e7814231 is a HUGE number! It's 2.97 x 10^7814233...
Python doesn't handle numbers will nearly 8 million digits, and instead treats them as if they were infinity. That's why it says `inf`.

If you were to type `297e7814231` into a Python interpreter, you'd see `inf` there too for the same reason.

**Comment by alkuzad** [comment]
@dbieber it is funny 'bug' indeed as every commit SHA starting with number will be interpreted by Fire as number, raising "inf". As Fire does not use types annotations you can't really force argument to be interpreted as string, unless you want to tell every developer in company to escape quotes :D

Funny way to fuck up production, new day, new argparse is better day :D

**Comment by dbieber** [comment]
Oh! That is a terrible bug waiting to happen.

If you need to support that use case today you can use @fire.decorators.SetParseFn(str), but we're not ready to commit to that API for the long haul yet.

I sure hope that bug hasn't bitten you!

**Comment by alkuzad** [comment]
@dbieber errors happen anywhere :) 

thanks for pointing that out, it is well hidden in code :) I coded annotate parser if anyone gets into this problem:

```python
import inspect
import fire
from fire.decorators import _SetMetadata, GetParseFns, FIRE_PARSE_FNS

def SetAnnotateFns(fn):

    def wrapper():
        parse_fns = GetParseFns(fn)
        spec = inspect.getfullargspec(fn)

        parse_fns['positional'] = [spec.annotations[arg] for arg in spec.args if arg in spec.annotations]
        parse_fns['named'].update(spec.annotations)

        _SetMetadata(fn, FIRE_PARSE_FNS, parse_fns)
        return fn
    return wrapper

def annotation_test_bad(commiter, tag):
  print(f"Commited by: {commiter}, hash: {tag}")

@SetAnnotateFns
def annotation_test_ok(commiter: str, tag: str):
  print(f"Commited by: {commiter}, hash: {tag}")

def main():
    fire.Fire({'ok': annotation_test_ok, 'bad': annotation_test_bad})

if __name__ == '__main__':
    main()

# C:\Users\dawid.goslawski>python test_fire.py bad --commiter arthur --tag 0938e555
#Commited by: arthur, hash: inf

# C:\Users\dawid.goslawski>python test_fire.py ok --commiter arthur --tag 0938e555
#Commited by: arthur, hash: 0938e555
```
