### ISSUE TITLE
What is the practical use of the python-fire？

### ISSUE THREAD

**Issue by wjizhong** [google/python-fire#146]

**Comment by dbieber** [comment]
I most frequently use Python Fire to speed up developing and debugging Python code as I'm iterating on it. For example, as I'm making changes to a new module, I will test those changes frequently from bash via Python Fire without having to update my main method between runs. This allows me to develop much faster than without Fire. If I want to do more complicated things than running individual functions, I'll tack on the `-- -i` flag and play with the module I'm developing in IPython.

I also often use Python Fire for testing out other people's code quickly. Just calling Fire on their module let's me start messing with their module from bash or from Python.

And Fire of course also enables you to very quickly create a CLI from any Python code. This is Fire's headline use case. You have a bunch of functions and you want to use them in bash scripts or send them to a colleague who isn't a Python programmer? Just add one line and you're good to go.

Fire's focus so far has definitely been on time saving, and now with the current developments we're working on improving the "production value" of Fire CLIs. Of next big step in that direction is improving the help and usage screens to feel like a more professional CLI (and to feel less like an error message, as the current help screen sometimes does :)).
