### ISSUE TITLE
How strings are processed in fire.

### ISSUE THREAD

**Issue by Scsourav18** [google/python-fire#162]
I exposed a method(which takes a string as input parameter) to command line and called the method by passing "D:\test" as parameter value and below is the function body.
```
path=str(path).strip()
path=os.path.normpath(path)
print(path)
print(os.path.isdir(path))
```
Here the output is 
```
D:\test
true
```
if i hardcode parameter value in the method as:
```
path="D:\test"
path=str(path).strip()
path=os.path.normpath(path)
print(path)
print(os.path.isdir(path))
```
the output is 
```
D:       est
False
```
Here the "\t" is treated as special character.

Can someone please guide on this
Thankyou.

**Comment by dbieber** [comment]
In a standard Python string \t is the tab character.
If you instead use a raw Python string r"D:\test", or if you escape the backslash "D:\\\\test", then you'll get the string you want `D:\test`.

**Comment by Scsourav18** [comment]
Thanks for the quick response. But my initial query was passing the same string "D:\test" from command line and using same string from my code(hardcoding the string) give different results. Are the strings that are passed from command line as parameter are raw strings ?

**Comment by dbieber** [comment]
The shell has its own rules for parsing strings that get applied before
Python is even invoked. These rules mostly applied to handling quotes. So
no, the command line doesn’t use raw strings strictly speaking.

Once Fire receives the input arg from the shell, it may parse it as another
type (int, bool, etc), but in your case it sees it is a string and leaves
in unchanged.

When you instead pass the argument hardcoded in Python, Python treats it as
a string according to python’s rules for literals before it gets passed to
fire. It’s in these rules that “\t” means TAB whereas “\\t” or r”\t” mean
“\t”.
