### ISSUE TITLE
Generated usage strings should conform to the docopt format where possible

### ISSUE THREAD

**Issue by waldyrious** [google/python-fire#17]
Previously acknowledged by @dbieber as a possible improvement [here](https://plus.google.com/u/0/+WaldirPimenta/posts/Ving8QL2A2M).

**Comment by elly44** [comment]
It is nice.I like it.

**Comment by dbieber** [comment]
We've revamped our help and usage screens substantially.

They don't look like docopt, but I think you'll find they look quite nice :).
Always looking for feedback to improve them though, especially as they're quite new still.

We _do_ support parsing your docstrings now though, including but not limited to the format parsed by docopt, so I think you'll be pleased by that. E.g. if you include a description of params in your docstring, that'll show up as the param's description in the help screen. Lmk what you think.
