### ISSUE TITLE
New release of python fire.

### ISSUE THREAD

**Issue by pranavgupta1234** [google/python-fire#173]

**Comment by alexshadley** [comment]
Second this.  There's some functionality I built last fall that I'd love to be able to access.

**Comment by dbieber** [comment]
We're getting closer! Probably less than 1 month away at this point.

**Comment by dbieber** [comment]
Aiming to do the release on July 26. 🔥
Still have a handful more changes to get in though, so not a hard commitment.

**Comment by Janeenm** [comment]
https://raw.githubusercontent.com/google/python-fire/master/fire/completion.py 

Sent from Yahoo Mail for iPhone


On Friday, July 19, 2019, 3:39 PM, David Bieber <notifications@github.com> wrote:


Aiming to do the release on July 26. 🔥
Still have a handful more changes to get in though, so not a hard commitment.

**Comment by dbieber** [comment]
We're live! Release notes: https://github.com/google/python-fire/releases/tag/v0.2.0

`pip install -U fire` to upgrade.
