### ISSUE TITLE
An Odd Use Case: Using Fire from an App's Internal Python

### ISSUE THREAD

**Issue by ColinConwell** [google/python-fire#174]
I have a bit of an odd use case: I'm trying to include fire in a script that will be executed by the internal python of Blender, a 3D animation software.

Typically, this works by calling the following in a terminal:

`blender --background 'some-script.py' --python 'name_of_python_script.py' -- <arguments to python script>`

When I attempt to use Fire in this context, it seems to parse the initial commands passed to Blender in addition to the arguments passed after the python tag, giving me the following trace:

<img width="780" alt="Screen Shot 2019-05-06 at 11 26 09 PM" src="https://user-images.githubusercontent.com/23064382/57269680-59f15f80-7056-11e9-816e-cbf16820bae9.png">

I reckon it might not actually be possible to troubleshoot this, but I thought I'd throw it out there in case anyone is trying to use Fire in a similar way (or has done so successfully).

**Comment by dbieber** [comment]
Fire uses sys.argv by default unless the command= arg is passed to the call to Fire.
If you want to filter out some args and only pass other args to Fire, do the filtering in Python and then call `fire.Fire` with `command=filtered_args`.

**Comment by ColinConwell** [comment]
Thanks very much for the response. Could you provide a small example? I can't find documentation for the `command=filtered_args` in the examples.

**Comment by dbieber** [comment]
Here's a simple example of using the command arg:

`customargs.py`
```
import fire
import sys

def f(x, y):
  return 2*x + y

def main(args):
  binary_name = args[0]
  custom_arg = args[1]
  remaining_args = args[2:]
  print(binary_name)
  print(custom_arg)
  fire.Fire(f, command=remaining_args)

if __name__ == '__main__':
  main(sys.argv)
```

```
> python customargs.py hello 1 2
customargs.py
hello
4
```

In your case, you'll want to split args on '--' and pass only the args after the *first* '--' to Fire.

**Comment by ColinConwell** [comment]
Beautiful. This works like a charm. Thanks very much for your assistance. I'll mark this as closed, I think?
