### ISSUE TITLE
installing from source code / ModuleNotFoundError: No module named 'fire.console'

### ISSUE THREAD

**Issue by nanondev** [google/python-fire#175]
Hello guys, I am checking out fire source code to see if I can contribute anything to it. I tried to install from source code using GIT ,  and installing with setup.py (using python 3.7) and **I got the following error: ModuleNotFoundError: No module named 'fire.console'** , can anyone give me a hand ? thanks.

C:\web-mios\oss\python-fire\_tasks\test>python calculator.py double 10
Traceback (most recent call last):
  File "calculator.py", line 1, in <module>
    import fire
  File "C:\Users\aspire\AppData\Local\Programs\Python\Python37\lib\site-packages\fire-0.1.3-py3.7.egg\fire\__init__.py", line 21, in <module>
    from fire.core import Fire
  File "C:\Users\aspire\AppData\Local\Programs\Python\Python37\lib\site-packages\fire-0.1.3-py3.7.egg\fire\core.py", line 73, in <module>
    from fire.console import console_pager
ModuleNotFoundError: No module named 'fire.console'

C:\web-mios\oss\python-fire\_tasks\test>

**Comment by nanondev** [comment]
I found the cause, I write below how I fixed it in case anyone has the same problem: 

**in the installation folder for Fire, after setup, there "console" folder is missing.  I just copied the fire/console folder from the sources to the setup folder.** 

In my setup, that folder is: 
C:\Users\aspire\AppData\Local\Programs\Python\Python37\Lib\site-packages\fire-0.1.3-py3.7.egg\fire

 I will try to patch the setup script to make it work correctly.

**Comment by nanondev** [comment]
It seems that someone tried to fix it already but the pull request failed:

https://github.com/google/python-fire/pull/167

**Comment by dbieber** [comment]
Fixed
