### ISSUE TITLE
allow --flag to be aliased as -f

### ISSUE THREAD

**Issue by terrdavis** [google/python-fire#177]
I would like to manually specify single-dash aliases to parameters.

```python
# app.py
import fire
@fire.Fire(verbose="v")
def app(verbose=False):
    # do things
```
`python -m app -v` -> `verbose = True ` 

bonus: `python -m app -vv` -> `verbose = 2`  
equivalent: `python -m app --verbose=2`

**Comment by dbieber** [comment]
This is supported on master and will be available in the next release.

Specifically, we now support passing flags using only the first letter of the flag, provided doing so is not ambiguous. We don't support -vv for verbose=2 at this time.

**Comment by kkasra12** [comment]
Hello, I can't find this feature in the documentation. Can I have more info on how we use aliases in our codes? Also, I have found #429 which is closed with no further discussions.
