### ISSUE TITLE
[Question] How to turn off "Fire trace"?

### ISSUE THREAD

**Issue by ndaidong** [google/python-fire#178]
After a correct setting up, if we run a wrong command, Fire prints out the logs:

```
Fire trace:
1. Initial component
2. ('Cannot find target in dict:', 'versions', {'add': <function add at 0x7f1443c699d8>, 'multiply': <function multiply at 0x7f1443c7d6a8>, 'version': <function version at 0x7f14442f79d8>})

Type:        dict
String form: {'add': <function add at 0x7f1443c699d8>, 'multiply': <function multiply at 0x7f1443c7d6a8>, 'version': <function version at 0x7f14442f79d8>}
Length:      3

Usage:       abc 
             abc add
             abc multiply
             abc version
```

How can we turn off `Fire trace`, `Type`,  `String form`, and `Length`  sections for production usage? How can we replace them with more meaningful messages?

**Comment by dbieber** [comment]
Improvements to this screen and the help screen are coming in the next release.

If you're running Fire from source you can see them by adding:
```
  from fire import helptext
  fire.helputils.HelpString = helptext.HelpString
```
before calling fire.Fire.

It's not totally ready yet, but early feedback is certainly welcome.

**Comment by ndaidong** [comment]
@dbieber thank you

I got the error:

```
ImportError: cannot import name 'helptext'
```

I've built another version for myself, without debugging. My fork works well, it no longer print logs even wrong argument name. However, when I run without any argument, it show all the component like below:

```
ndaidong@xu19 /workspace $ mycli
add:      <function add at 0x7fbcb3146a60>
multiply: <function multiply at 0x7fbcb3160840>
version:  <function version at 0x7fbcb35040d0>
```

How can I disable this behaviour? In this case, I expect it show the help message instead.

**Comment by dbieber** [comment]
In 59dd4e028cef7046201ef9a19445a4e6c3073c11 we turn off showing the trace by default on an error.

As for the output like
```
add:      <function add at 0x7fbcb3146a60>
multiply: <function multiply at 0x7fbcb3160840>
version:  <function version at 0x7fbcb35040d0>
```
that's on our list to improve too.
For now though, the best way to improve that is to use a class rather than a dict.

So,
```
class CLI:
  def add(self, args): ...
  def multiply(self, args): ...
  version = ...

fire.Fire(CLI)
```

(Closing the issue, but feel free to reply or ask more questions)

**Comment by ndaidong** [comment]
@dbieber I got it now, thank you.
