### ISSUE TITLE
Suppress printing of function return

### ISSUE THREAD

**Issue by mauriceling** [google/python-fire#179]
Let's say I have a Fire exposed function

def X(paramA):
    return {'paramA': paramA}

Fire will automatically print out the function return to the screen. It is possible to suppress the printing of function return?

**Comment by dbieber** [comment]
Can you say a bit more about how this function is used?

If its only used by fire, you could just remove the return statement (since the return value isn't being used elsewhere anyway).
If its used by fire and in other ways, you could wrap X in a function that calls X and returns nothing, e.g.:

```
def X_cli(paramA): X(paramA)
fire.Fire(X_cli)
```

**Comment by mauriceling** [comment]
Essentially, this function is to be used as both API and CLI. Hence, I will need the function to return a list of dictionaries for use as API. However, as CLI, the printout of the returned list of dictionaries is ugly. Therefore, I am looking for a way to suppress the printing of returned values (list of dictionaries) when the function is used as CLI as I will use a set of print functions to print it nicely on the screen.

**Comment by dbieber** [comment]
Makes sense.

What are the types of the values in your returned dictionary?

It's on our list of TODOs to improve how dicts get printed. The current thinking is to leave the current method of printing dicts when the keys and values are all simple types, but to use the help screen (which is recently improved, and will come out in the next release) when the dict contains more complex types like functions, objects, etc. Would this solution help in your situation?

**Comment by dbieber** [comment]
We've moved forward w/ this approach (showing the help screen when a dict contains complex types) and it will be available in Friday's release.

**Comment by imdadahad** [comment]
Having the same issue. Not ideal to see 'ugly' `dict` payloads to be printed on the screen. 

Is there any workaround?

**Comment by ckrapu** [comment]
Same here - I started a decorator to check to see if the function is being called from Fire or somewhere else; any ideas on how to check that in a stable way?

**Comment by dbieber** [comment]
https://github.com/google/python-fire/pull/345 will be available in the next release and may provide what you're looking for
