### ISSUE TITLE
Way to use one/no separator/hyphen in help/usage

### ISSUE THREAD

**Issue by fedorbirjukov** [google/python-fire#195]
Landed here due to flags. I know it's documented that "--flag1 --flag2" does not work.
But since "-flag1 -flag2" and "flag1 flag2" do work, I wanted to ask if there's a way to have one/no hyphen in front of an argument in the generated Usage text. Also, it makes sense to skip the value (all caps) for named flags in Usage text.

Here is what we have now:
```
Usage:       util build [FORCE] [NO_RM]
             util build [--force FORCE] [--no-rm NO_RM]
```

Here is what it could be like:
```
Usage:       util build [FORCE] [NO_RM]
             util build [-force] [-no-rm]
```

Another remark: separator is not used in Usage text, it's always hyphen (hard-coded).

What do you think?

**Comment by fedorbirjukov** [comment]
"-flag1 -flag2" and "flag1 flag2" do not work. => having one/no hyphen does not make any sense.

**Comment by fedorbirjukov** [comment]
skipping value would make sense if "--flag1 --flag2" worked... but it does not. only one flag can be used like that.

**Comment by fedorbirjukov** [comment]
Feels a bit strange.

This works as expected:
- -force
- -force -no-rm
- -no-rm -force

This does not:
- -no-rm (sets force to true, does not set no_rm to true)
- -no-rm -no-rm (sets force to true, and no_rm to true)

Is that supported or not?

**Comment by dbieber** [comment]
> Another remark: separator is not used in Usage text, it's always hyphen (hard-coded).

If that's the case, that's a bug. Thanks for catching it.
Will look at the rest of the report later and respond more fully.

**Comment by fedorbirjukov** [comment]
> > Another remark: separator is not used in Usage text, it's always hyphen (hard-coded).
> 
> If that's the case, that's a bug. Thanks for catching it.
> Will look at the rest of the report later and respond more fully.

That's not the case... And the rest of this bug report is messy and hard to reproduce. Will provide more details and a reproduction scenario.

**Comment by fedorbirjukov** [comment]
Python v3.6.5
Windows 10.0.17763.0
Fire 0.1.3

Sample code:
```
import fire

def f(self, no_rm=False):
    print('no_rm=%r' % (no_rm))

fire.Fire()
```

`util --no-rm` results in:
```
no_rm=False
Fire trace:
1. Initial component
2. Accessed property "f"
3. Called routine "f" (.\devel_config\docker\image_builder\pfire.py:4)
4. ('Could not consume arg:', '--no-rm')

Type:        NoneType
String form: None

Usage:       pfire.py f -
```

`util --no_rm` works:
```
no_rm=True
```

**Comment by fedorbirjukov** [comment]
In Fire 0.2.1 everything works as expected. Not sure how I ended up with this older version. Closing the issue.
