### ISSUE TITLE
Taking hidden arguments

### ISSUE THREAD

**Issue by i-amgeek** [google/python-fire#210]
Is there any method to get hidden input in arguments? Or any technique to use getpass with fire?

**Comment by dbieber** [comment]
There's no special support for this built in to Fire, but you can of course do something like:

```
import fire, getpass

def login(username, password=None):
  if password is None:
    password = getpass.getpass()
  auth(username, password)

if __name__ == '__main__':
  fire.Fire(login)
```

You can also write a decorator that does this too. Decorators that modify how arguments are handled often work very well with Fire.

e.g.
```
def hidden_input(fn):
  def wrapper(*args, **kwargs):
    if kwargs.get('password') is None:
      kwargs['password'] = getpass.getpass()
    return fn(*args, **kwargs)
  return wrapper

@hidden_input
def login(username, password=None):
  auth(username, password)

if __name__ == '__main__':
  fire.Fire(login)
```

An advantage of this approach is that you can continue using the `login` function normally from within python, but at the command line it gives you the behavior that you're asking for.

**Comment by dbieber** [comment]
Closing, but feel free to keep the conversation going.
