### ISSUE TITLE
Define a default command

### ISSUE THREAD

**Issue by Freakwill** [google/python-fire#214]
Is it sensible to define a default command, if dose not lead to any conflict?

```python
# in script foo.py
def foo():
    print('foo')
def bar():
    print('bar')
def main():
    print('main')
```
It the rule is running a command with the same name to the script, then
command `$ foo.py` will run `foo` function by default. If the rule is running command `main` that was defined, then run it.

**Comment by dbieber** [comment]
This is tricky to add to Fire because it will often lead to ambiguous situations.

For example, let's say we modify your example a little:

```
def foo():
    print('foo')
def bar():
    print('bar')
def main(name):
    print('main ' + name)
```

Suppose main is the "default command" but the user runs `$ example.py foo`. Does Fire call `foo()`, or do we call `main('foo')`? It's ambiguous.

**Comment by me21** [comment]
@Freakwill I think you can achieve what you want with the following code snippet:

```python
    import sys

    if len(sys.argv) == 1:
        # No arguments provided, run directly
        run_default_command()
    else:
        # Arguments provided, use Fire to handle commands
        fire.Fire(...)
```
