### ISSUE TITLE
A set of MVC WEB framework designed based on Google Python-fire,Flask,RPyC

### ISSUE THREAD

**Issue by lifeblood** [google/python-fire#217]
https://github.com/lifeblood/fire-cli.git

**Comment by dbieber** [comment]
Thanks for sharing this.

**Comment by lifeblood** [comment]
So, bro, give me a start.

**Comment by dbieber** [comment]
If you have any issues with or questions about using Python Fire, feel free to post them here. Otherwise, best of luck with your project -- I think the idea behind your project is really neat.
