### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by XenGi** [google/python-fire#219]
So, I just found this project. It looks pretty cool, so I copied the example into a file called `fire.py` with the content:

```python
#!/usr/bin/env python3

import fire

class Calculator(object):
  """A simple calculator class."""

  def double(self, number):
    return 2 * number

if __name__ == '__main__':
  fire.Fire(Calculator)
```

In my fresh virtualenv I do `pip install fire`. After that I fire everything up:

```
$ chmod +x fire.py
$ ./fire.py
Traceback (most recent call last):
  File "./fire.py", line 12, in <module>
    fire.Fire(Calculator)
AttributeError: module 'fire' has no attribute 'Fire'
```

This is your minimal example in your README file. How can this not work? m(

**Comment by dbieber** [comment]
The problem is that you've named your module `fire`, which conflicts with using this library which is named `fire`.
Rename your module to e.g. `example.py` and everything should work.
