### ISSUE TITLE
Support flag-only arguments

### ISSUE THREAD

**Issue by MaxG87** [google/python-fire#221]
I would like to have arguments that do not accept any value. Thus,

    ./my-script.py --flag

should work, but

    ./my-script.py --flag SomeValue

should not. In `argparse` this can be achieved by 

    parser.add_argument("--flag", action="store_true")

but I do not know how to achieve that in python-fire.

**Comment by dbieber** [comment]
**Current status**

```
./my-script.py --flag
```
should work already,
however 
```
./my-script.py --flag SomeValue
```
will also be accepted by Fire.

-------

**Possible workaround**

You can raise a FireError in your function if you receive an invalid input with a message for the user to indicate an input error.

Using this strategy you can write decorators for yourself to satisfy your needs.

E.g.
```python
import fire

def bool_only(fn):
  def fn2(arg):
    if arg not in [True, False]:
      raise fire.core.FireError('Invalid input, bool required.')
    return fn(arg)
  return fn2
```
```python
@bool_only
def my_script(value):
  return not value

fire.Fire(my_script)
```  

--------

**Possible Future Solution**

We're currently discussing adding a "strict" mode to fire, which uses type annotations or default values to do type checking. If this were enabled, then you could annotate an argument as a boolean and only a boolean could be passed. --flag=True would still work, but --flag=SomeValue would not.
