### ISSUE TITLE
Python 2.7  while loop issue, (list index out of range)

### ISSUE THREAD

**Issue by NicholasMatthews** [google/python-fire#234]
`searchlist = []
import sys #imported the sys function to enable the printing of a variable multiple times on the same line during a loop
nconverted =[]
converted = []
words = []
n = 0
A = 1
B = 0
push = 0

def numberconvert():
    n = 0
    ciphertext = ["U","O","M","Q","Q","K","F","X","A","C","K","H","C","X","M","P","F","A","Y","H"]
    while n < 20:
        pos = ciphertext[n]
        number = ord(pos) -66
        converted.append(number)
        n = n + 1
    print converted
numberconvert()

def loop():
    A = ["1","9","21","15","3","19","7","23","11","5","17","25"]
    n = 0
    B = 0
    push = 0
    x = 0
    i = 0
    for x in range(6240):
        if n == 19:
            n = 0
        push = ((int(A[i])) * (int(converted[n])) - B)%26
        n = n + 1
        B = B + 1
        if B == 26:
            i = i + 1
            B = 0
        x = x + 1
        finalkey = chr(ord('@')+ push)
        nconverted.append(finalkey)
        sys.stdout.write(finalkey)
                
`

I don't understand why i've getting an output of list index out of range, I understand that B is the issue whoever I just don't know how to fix it so then it provides the sufficient 6240 outputs

Hope someone can help me here! 

Thanks for your time

**Comment by dbieber** [comment]
If you use triple backticks (\`\`\`) in your comment around your code, then it will be formatting properly.

**Comment by dbieber** [comment]
Also, this Issues section is for issues related to Python Fire, so I'm going to close the issue.
Good luck in solving your problem!
