### ISSUE TITLE
Not working when we install as a package,when i Move cli script to /usr/local/bin.

### ISSUE THREAD

**Issue by kodani** [google/python-fire#24]
I made one script teacount.py.
In the file, It has two functions. The script is working fine until I moved it to scripts folder with setup.py, So I can access it from anywhere.

But it's giving error as follows.
```
/usr/local/bin/teacount.py: line 6: syntax error near unexpected token `('
/usr/local/bin/teacount.py: line 6: `def countme(name):'
```
you can install to check by following link.
[my project link](https://github.com/kodani/TeaCounter)

**Comment by dbieber** [comment]
Maybe you aren't running it as Python. You could try adding #!/usr/bin/env python to the start of teacount.py.

**Comment by kodani** [comment]
Solved🙈😅
