### ISSUE TITLE
example in docs for grouping has no output

### ISSUE THREAD

**Issue by MSAdministrator** [google/python-fire#240]
Hello, following the docs here: https://github.com/google/python-fire/blob/master/docs/guide.md#grouping-commands

I am unable to get this to run when calling 

```python
example.py run
```

It currently returns no output.

If I run either of the `digestion run` or `ingestion run` commands they work flawlessly just not the grouped command 

Heres the code:

```python
import fire

class IngestionStage(object):

  def run(self):
    return 'Ingesting! Nom nom nom...'

class DigestionStage(object):

  def run(self, volume=1):
    return ' '.join(['Burp!'] * volume)

  def status(self):
    return 'Satiated.'

class Pipeline(object):

  def __init__(self):
    self.ingestion = IngestionStage()
    self.digestion = DigestionStage()

  def run(self):
    self.ingestion.run()
    self.digestion.run()

if __name__ == '__main__':
  fire.Fire(Pipeline)
```

**Comment by dbieber** [comment]
Can you provide an example of a failing command?

If you run

```
python code/playground/sillyfire.py digestion status
```
you should see
```
Satiated.
```

Is that not working for you, or is it something else?

**Comment by dbieber** [comment]
Oh, is it `python example.py run` that isn't working?

That command doesn't output anything, because it neither prints nor returns anything. We should update the docs so that it does something...

**Comment by MSAdministrator** [comment]
@dbieber Yep, that clears it up!  Thanks for the quick response!

**Comment by dbieber** [comment]
It does. Both ingestion.run() and digestion.run() both get called (because Pipeline().run() is called). Just nothing is displayed, since Pipeline().run() doesn't return anything (and nothing prints along the way).

If Pipeline().run() returned something, it would be displayed.

**Comment by MSAdministrator** [comment]
Ahh, okay I missed that those classes are returning and not printing - my bad - yep that makes sense.

Modified the example to just print and its working - derp on my part:

```
class Pipeline(object):

  def __init__(self):
    self.ingestion = IngestionStage()
    self.digestion = DigestionStage()

  def run(self):
    print(self.ingestion.run())
    print(self.digestion.run())

if __name__ == '__main__':
    fire.Fire(Pipeline)
```

**Comment by rajpratyush** [comment]
@dbieber does this issue needs work?? if so can you tell me how to get started with it?

**Comment by dbieber** [comment]
Hi @rajpratyush 

The steps for this issue are to read the grouping commands section of the docs, figure out where it is unclear, and propose a change to clarify it.
One simple resolution would just be to add `return "Pipeline complete."` at the end of the `run` function. in the `Pipeline` class. I think having that there would make it clearer that the pipeline has indeed run successfully even though it hasn't displayed anything along the way.
Would you like to do that?

**Comment by rajpratyush** [comment]
@dbieber yes sir surely I would like to do the issue but do you mind if start working on after 2nd march. I have my exams currently going on

**Comment by dbieber** [comment]
Not a problem. 👍

**Comment by rajpratyush** [comment]
@dbieber can you just point the file to begin with ?

**Comment by dbieber** [comment]
python-fire/docs/guide.md
