### ISSUE TITLE
Use Fire with Python3

### ISSUE THREAD

**Issue by RilDev** [google/python-fire#246]
Hi there,

I'm new to Python and I was wondering if we could download Fire for Python3?

My goal is to make a Pip package using Fire and Python3.

Thank you very much!

**Comment by dbieber** [comment]
Yes! Python Fire works great with Python 3.

Once you have pip set up, you can simply `pip install fire` to install Python Fire.

Good luck!

**Comment by RilDev** [comment]
Thank you for the quick reply @dbieber,

I did a test project and it works well with `python` but not with `python3`.

Plus when I installed the `fire` package I got a warning saying that the version `python 2.7` will not be supported for long. Is it something I should be concerned with?

**Comment by dbieber** [comment]
Try `pip3 install fire`. It sounds like you've only installed fire for your Python 2 setup, not your Python 3 setup. Python environments can be really tricky. If you haven't looked into virtualenv or pyenv yet, I recommend using one of those.

**Comment by RilDev** [comment]
It worked, thank you!

Ok, I'll look into `virtualenv` and `pyenv` :)

**Comment by RilDev** [comment]
Hi there @dbieber!

Thanks for the advice about the python environment managers. I settled for [pyenv](https://github.com/pyenv/pyenv) and [pipenv](https://github.com/pypa/pipenv).  

Just as a follow up, I was able to publish my package on [pypi.org](https://pypi.org/project/gospel/)!

Finally I went for the [PyInquirer](https://github.com/CITGuru/PyInquirer) package for the ability to do interactive lists (I couldn't figure out how to do it with Fire).

And voila! Here is the project (in it's early stages) [https://pypi.org/project/gospel/](https://pypi.org/project/gospel/)!

For reference for other beginners in python:
- I learned the basics of python with this FreeCodeCamp article: [https://www.freecodecamp.org/news/the-python-guide-for-beginners/](https://www.freecodecamp.org/news/the-python-guide-for-beginners/)
- I used this tutorial for the publishing process: [https://realpython.com/pypi-publish-python-package/](https://realpython.com/pypi-publish-python-package/),
