### ISSUE TITLE
module 'fire has no attribute 'Fire'

### ISSUE THREAD

**Issue by uhMale** [google/python-fire#268]
I know people have run into this issue and it was fixed by renaming the module from fire.py to something else. I don't have a module named fire and still can't get past this error. I've tried it on a windows 7 and windows 8 machine. I've also spun up two ubuntu 18.04 VM's on those windows hosts but I can't get past this error. Does anyone have any suggestions for me? If there is a better place to ask this please let me know. Thanks.

**Comment by dbieber** [comment]
After running `import fire`, run `fire.__file__` to see where fire is being imported from. Also run `fire.__version__` in case there's a version number available. The output of these two expressions should be helpful in debugging the issue.

**Comment by uhMale** [comment]
Thanks! I looked into that and everything checked out. I finally just reinstalled fire and it now it's working fine. Weird that it happened on all those machines but it's certainly not an issue anymore. Thanks again!
