### ISSUE TITLE
Fire behaviour on spliting strings into tuples

### ISSUE THREAD

**Issue by 1MLightyears** [google/python-fire#270]
I'm using Fire to handle CLI variables in my project, while I found Fire has different actions for strings including commas.
When a string does not include commas, it will be transferred to a variable as a whole. But if the string includes commas, it will be split into parts and be transferred to a variable as tuple.
example:
```python
# in firetest.py
from fire import Fire

def func(a:str=''):
   print(type(a))

Fire(func)
```
When testing
```bash
$python firetest.py --a qwerty # <class 'str'>, a='qwerty' ← good√
$python firetest.py --a qwe,rty # <class 'tuple'>, a=('qwe','rty') ← not so good!
```
This is kinda annoying...because my index to a variable may be totally different things, base on different user inputs.
So I'm wondering if there is any switch to stop parsing commas as delimiters and let me handle user input for consistency?

**Comment by sharvanir** [comment]
Hi, this looks like an issue in python ast module, which is splitting that string into two nodes, or some of that sort. Looking into this, please hang on.

**Comment by 1MLightyears** [comment]
It's getting even more weird...I still take the same example above:
```bash
$$python firetest.py --a "qwe,rty" # <class 'tuple'>, a=('qwe','rty')
$python firetest.py --a "q w e,rty" #<class 'str'>, a='q w e,rty'
```
I found this when I was trying to take space into my arguments, and found that as long as the string includes space, it will be parsed as a string, but no! I was looking for it being parsed as a tuple for I inserted comma between words!
Even
```bash
$python firetest.py --a "(q w e,rty)"
``` 
Will return 
```bash
<class 'str'># a=(q w e,rty)
```
But
```bash
$python firetest.py --a "('q w e','rty')" 
```
Will return
```bash
<class 'tuple'># a=('q w e','rty')
```
That is too complex and way too user-unfriendly. Any solutions? Or I can overload anything to avoid this?

**Comment by dbieber** [comment]
You can use `@fire.decorators.SetParseFn(str)` to change the parse function so that it always parses an argument as a string. Heads up this is experimental though, and the API may change in a future version.

**Comment by 1MLightyears** [comment]
@dbieber Thank you very much, It works pretty well 😆 
Now I have full control of the arguments inputted and that is exactly what I need. Thanks again!
