### ISSUE TITLE
components-extension

### ISSUE THREAD

**Issue by stroupbslayen** [google/python-fire#273]
Hi,

I just got introduced to this project and am really liking it so far, it's got a lot of potential, is relatively simple to understand and get up and working for something simple. Organization was a problem I ran into pretty quickly though and expanding into a larger project the process didn't really click for me for how to to get stuff working the way I would have liked. To solve this I forked the project and put together a [components-extension](https://github.com/stroupbslayen/python-fire/tree/component-ext). It could still use some documentation but it seems to be working with what I've tested.

Basically using decorators to help the flow of creating different commands and groups for an app like this:

``` python
import fire
from fire.ext import components

component = components.Component()

# create a new group the belongs to the component
basic_math = component.new_group("Basic Math")

# add a command to a group
@basic_math.command(name="add")
def adder(a, b):
    return a + b

if __name__ == "__main__":
    fire.Fire(component.build(), name="Example")
``` 
And you can run 
``` cmd
python file.py Basic_Math add 3 4
>>> 7
```

It might not be super useful for very simple apps but when expanding I think it makes things very easy to work with.

It's not working directly with `fire` though, so I'm not sure if it's something that should be implemented with it or just kept separate but I thought I'd mention it anyways.

Thank you!

**Comment by dbieber** [comment]
Awesome!

Thanks for sharing this. I'll take a closer look at your project soon, but at a glance I like the premise :).

**Comment by dbieber** [comment]
The link to your project doesn't work and I don't see it in your repositories (https://github.com/stroupbslayen?tab=repositories). Perhaps you made it private or deleted it.
