### ISSUE TITLE
ImportError: No module named fire.

### ISSUE THREAD

**Issue by alejandra-gutierrez** [google/python-fire#284]
I run the command 
`pip3 install fire` and then run the hello.py script shown in the tutorial. This is the error message that I get: 

```
bluebee@bbench:~$ python hello.py
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    import fire 
ImportError: No module named fire.
```

**Comment by dbieber** [comment]
Try running `python3 hello.py` since you installed fire with pip3.

If that doesn't work, please run `type python` and `type pip3` and share the results here to help debug the issue.

**Comment by dbieber** [comment]
Feel free to reopen this issue if you'd like more help debugging.
