### ISSUE TITLE
Default to certain command if none is given at CLI

### ISSUE THREAD

**Issue by MaxG87** [google/python-fire#285]
Consider the following MWE program:

```
#!/usr/bin/env python3

import fire

def print_bla():
    print("Bla")

def print_blubb():
    print("Blubb")

def print_plopp():
    print("Plopp")


if __name__ == "__main__":
    fire.Fire()
```

I want to achive that if I invoke it without any arguments (`./firetest.py`) it executes `print_plopp()` (or some other function I chose).

Right now I do not see how this can be achieved. Is it possible at all?

**Comment by MaxG87** [comment]
So, I found a way, but I do not like it. One has to create a CLI class and nest the functions of interest inside it. Then one can call the default from __call__, which will be called when no argument is given. However, I find this unnecessarily complex and would be glad about a more elegant way.

```
#!/usr/bin/env python3

import fire

def print_bla():
    print("Bla")

def print_blubb():
    print("Blubb")

def print_plopp():
    print("Plopp")


if __name__ == "__main__":
    fire.Fire()
```

**Comment by nfultz** [comment]
I would probably do this manually by checking the number of arguments,
something along these lines:

    fire.Fire() if len(sys.argv) else print_plopp()

**Comment by MaxG87** [comment]
> `fire.Fire() if len(sys.argv) else print_plopp()`
In hindsight, this is the obvious and elegant solution. Thank you very much.
