### ISSUE TITLE
Allegro trains integration.

### ISSUE THREAD

**Issue by ramonemiliani93** [google/python-fire#291]
Hi, I am currently trying to integrate `python-fire` and `trains`. Trains, at the moment, is capable of automatically detecting the arguments when using `argparse`. I tried with fire but unfortunately the same does not happen. Could you point me to where the argument parsing happens in fire?

**Comment by dbieber** [comment]
The arguments are initially parsed here:
https://github.com/google/python-fire/blob/878b8d86f488ef2606cffdf58297dd2781708316/fire/core.py#L123

You can see how they're used in the `_Fire` function's large loop, described here:
https://github.com/google/python-fire/blob/878b8d86f488ef2606cffdf58297dd2781708316/fire/core.py#L366-L388

Let me know if you have further questions.

**Comment by bmartinn** [comment]
Thanks @dbieber !
It seems the [_ParseArgs](https://github.com/google/python-fire/blob/878b8d86f488ef2606cffdf58297dd2781708316/fire/core.py#L745) is where the magic happens, defining the names of the arguments, default values etc. Is this correct?

**Comment by dbieber** [comment]
Yes that's right.
You'll also want to take a look at
https://github.com/google/python-fire/blob/878b8d86f488ef2606cffdf58297dd2781708316/fire/core.py#L670-L671

^^That's the path for parsing arguments to a function. Fire also supports using command line arguments for e.g. accessing a member of an object too.
