### ISSUE TITLE
Hyphen vs underscore for variable names

### ISSUE THREAD

**Issue by ludovicschwartz** [google/python-fire#292]
One common thing is to have arguments made of multiple words, for instance `name of cat` that can written in 3 commons way :

- nameofcat
- name_of_cat
- name-of-cat

While the first one is compatible with pretty much everything, the second one should be avoided in bash (https://stackoverflow.com/questions/1253679/should-command-line-options-in-posix-style-operating-systems-be-underscore-style) and the third one in python (https://stackoverflow.com/questions/2064329/why-does-python-disallow-usage-of-hyphens-within-function-and-variable-names).

The problem here is that by default fire will take arguments name from the python code, which means that if my python code looks like this:

script.py:

    import fire
    def main(name_of_cat='Steve'):
        print(f'The name of the cast is {name_of_cat}')
    if __name__ == '__main__':
        fire.Fire(main)

then to call it from the command line (or from a bash script), one would do

    python script.py --name_of_cat Bob

This is the way I'm using it at the moment, but this feels suboptimal. Any idea on what the best practice is here ?

PS : `python script.py --name-of-cat Bob` would be impossible since python can't have hyphen in variable names.

**Comment by dbieber** [comment]
Both --name_of_cat and --name-of-cat should work:

```python
In [1]: import fire 
   ...: def main(name_of_cat='Steve'): 
   ...:     print(f'The name of the cast is {name_of_cat}') 
   ...:                                                                                                                                                                              

In [2]: fire.Fire(main, command='--name-of-cat=Dave')                                                                                                                                
The name of the cast is Dave

In [3]: fire.Fire(main, command='--name_of_cat=Dave')                                                                                                                                
The name of the cast is Dave
```

**Comment by ludovicschwartz** [comment]
Thank you very much for your answer. 
It is noted in the documentation and I just missed it :( :
[here](https://github.com/google/python-fire/blob/878b8d86f488ef2606cffdf58297dd2781708316/docs/guide.md) in the Fire docs:

> To instantiate a `Building` and then run the `climb_stairs` function, the following commands are all valid:
>
>     $ python example.py --name="Sherrerd Hall" --stories=3 climb_stairs 10
>     $ python example.py --name="Sherrerd Hall" climb_stairs --stairs_per_story=10
>     $ python example.py --name="Sherrerd Hall" climb_stairs --stairs-per-story 10
>     $ python example.py climb-stairs --stairs-per-story 10 --name="Sherrerd Hall"
>
>You'll notice that hyphens and underscores (`-` and `_`) are interchangeable in member names and flag names.

**Comment by district10** [comment]
> You'll notice that hyphens and underscores (- and _) are interchangeable in member names and flag names.

But how to make fire document show `--stairs-per-story` instead of `--stairs_per_story`?
