### ISSUE TITLE
Help Request - how to show cli's version?

### ISSUE THREAD

**Issue by zillionare** [google/python-fire#299]
If I build a cli tool (for example, called foo), how can I show foo's version by calling:

```
foo -v
# or the following:
foo --help
```

Thanks for help.

**Comment by nfultz** [comment]
If you write a function that prints out the version of your tool, Fire can invoke that function for you.

**Comment by zillionare** [comment]
at last use the trick to achieve this, but still would like to know if there's best practice:
```
# foo.py
import fire

def version():
    print("version is 0.1")

if __name__ == "__main__":
    fire.Fire({
        "--version": version
})
```
then run ``foo --version`` will got "version is 0.1"
