### ISSUE TITLE
google fire run @property automatically

### ISSUE THREAD

**Issue by spectereye** [google/python-fire#311]
i use google fire for cli, and met an issue below, could you please help?

```python
# test.py
import fire

class C:
    @property
    def foo(self):
        print('foo')

    def bar(self):
        print('bar')

fire.Fire()
```

then run as

```bat
python test.py C bar

foo
bar
```

as seen it print "foo" which is unwanted, any elegant way to solve this?

**Comment by spectereye** [comment]
close this ticket please, find this has been solved in latest fire

**Comment by dbieber** [comment]
Closed!
