### ISSUE TITLE
Chaining Function Calls breaks usage of default arguments values

### ISSUE THREAD

**Issue by AmmarRabie** [google/python-fire#313]
consider the [basic example](https://github.com/google/python-fire/blob/master/docs/guide.md#chaining-function-calls) at the guide docs. If any function has arguments with default values, we have to pass all of them first, then chain other calls. if you try to call the second function directly, this will be considered as overridden value of the arg. <br>
I have modified the basic example to illustrate my use case
``` python
import fire

class BinaryCanvas(object):
  """A canvas with which to make binary art, one bit at a time."""

  def __init__(self, size=10):
    self.pixels = [[0] * size for _ in range(size)]
    self._size = size
    self._row = 0  # The row of the cursor.
    self._col = 0  # The column of the cursor.

  def __str__(self):
    return '\n'.join(' '.join(str(pixel) for pixel in row) for row in self.pixels)

  def show(self):
    print(self)
    return self

  def move(self, row, col):
    self._row = row % self._size
    self._col = col % self._size
    return self

  def on(self):
    return self.set(1)

  def off(self):
    return self.set(0)

  def onVal(self, val=1):
    return self.set(val)
  def offVal(self, val=0):
    return self.set(val)

  def set(self, value):
    self.pixels[self._row][self._col] = value
    return self

if __name__ == '__main__':
  fire.Fire(BinaryCanvas)
```
Now, I expect we can use new methods `onVal`, `offVal` instead of `on` and `off`. e.g `python example.py move 3 3 onVal move 3 6 onVal move 6 3 onVal move 6 6 onVal move 7 4 onVal move 7 5 onVal`, but this will not work

**Comment by AmmarRabie** [comment]
I don't what is the best solution, for now I send default parameters again from the command line. may be adding another version of the function with default parameters embedded into its body will fine in some cases.
What I expect to find in the documentation of Fire, is to have special wildcard (e.g `$`) that we can append before command name to force interpret as command. But I didn't found

**Comment by nfultz** [comment]
Did you try using the seperator?


> You can use a separator to indicate that you're done providing arguments to a function. All arguments after the separator will be used to process the result of the function, rather than being passed to the function itself. The default separator is the hyphen -.
> 
> Here's an example where we use a separator.
> 
> $ python example.py dog cat elephant - upper
> CAT DOG ELEPHANT

**Comment by AmmarRabie** [comment]
Oh, thanks. I didn't catch it in the guide document. Worked with separator

**Comment by dbieber** [comment]
Yep, the separator is your solution!

Putting `-` in your command indicates that you're done providing arguments to a function. Any more arguments get passed to the result of the function. It's particularly useful when chaining commands that have default arguments (or varargs or kwargs).
