### ISSUE TITLE
Optional and required flags are swapped in the "Usage" message

### ISSUE THREAD

**Issue by Mirandatz** [google/python-fire#315]
Running python script.py command

```
import fire


class Example:

    def command(self, *, arg1: bool, arg2: bool = True, arg3: bool = False):
        pass


if __name__ == '__main__':
    fire.Fire(Example)

```

Prints

```
ERROR: Missing required flags: {'arg1'}
Usage: download.py command <flags>
  optional flags:        --arg1
  required flags:        --arg2 | --arg3
```

The "ERROR" message correctly points that arg1 is required, but the "Usage" message is swapping required and optional arguments.

**Comment by dbieber** [comment]
Thanks for reporting the issue!

**Comment by xavierfigueroav** [comment]
I would like to take this issue!

**Comment by dbieber** [comment]
Excellent, thanks xavierfigueroav. Let me know if you need any pointers to get started.

**Comment by xavierfigueroav** [comment]
I think I got it, it was very simple. I guess I have to write tests for the change. If so, I need pointers on how to simulate the call `python script.py command`. I think that the following component is the most suitiable for this case:
https://github.com/google/python-fire/blob/8e9b1d52132cfab5f789435a9d88bdf881bbbe22/fire/test_components.py#L125-L134
But, I don't know how to simulate the call to `identity` from it. Just `component = tc.MixedDefaults` or `component = tc.MixedDefaults.identity` doesn't seem to reproduce the case.

**Comment by xavierfigueroav** [comment]
It seems that the bare `*` actually matters :sweat_smile:. I need something like
```
class Example:
    def command(self, *, arg1, arg2=True, arg3=False):
        pass
```
So, should I add a function like that to the MixedDefaults component or create a new component?

**Comment by xavierfigueroav** [comment]
Well, I opened #316. If any changes are needed, please, let me know.

**Comment by dzieciou** [comment]
What's the progress on that? 1 year passed and still a problem
