### ISSUE TITLE
Feature request: shebang string for fire

### ISSUE THREAD

**Issue by c6401** [google/python-fire#319]
Would be nice to be able to use just shebang string and not import anything explicitly
like illustrated here:
```py
#!/usr/bin/env -S python3 -m fire

def ping():
    print('pong')
```

```sh
$ example.py ping
pong
```

**Comment by dbieber** [comment]
That should already work. :D

**Comment by c6401** [comment]
@dbieber
It does not, decided to debug more - the issue is `-m fire` expects to have python module notation path like if example.py will be in `~/bin` directory then the correct way to call it from ~ is 
```sh
python3 -m fire bin.example
```
but not
```sh
python3 -m fire /home/{user}/bin/example.py
```
And now after finding out why it doesn't I'm not 100% sure if it should be implement ¯\_(ツ)_/¯  
The problem that I see is ideally application should be in one of the dirs where python searches for modules but also script should start from $PWD.
This solution might work though:
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path  
the other option is to add script directory to PYTHONPATH which is hacky and i'm wondering how it will work on import if there will be __init__.py  
So then shebang string can be something like  
```sh
#!/usr/bin/env -S python3 python3 -m fire --file
```
where --file will use import by file directory  

Although if it's over-complicating the source code or seems like feature bloat or my concerns are valid the issue can be closed.

**Comment by nfultz** [comment]
> So then shebang string can be something like
> 
> ```shell
> #!/usr/bin/env -S python3 python3 -m fire --file
> ```
> 
> where --file will use import by file directory

Thanks for your detailed explanation. It might be cleaner to have two different __main__.pys, one for modules, one for scripts. something like this maybe? 


```shell
#!/usr/bin/env -S python3 python3 -m fire.sh script.py
```

**Comment by dbieber** [comment]
Make sure you're running the latest version of fire. In 0.4.0 we do support using `-m fire` with filepaths
```
python3 -m fire /home/{user}/bin/example.py
```

If it's still not working there, let me know

**Comment by c6401** [comment]
Yes, it works on 0.4.0! I had v. 0.3.1 apparently. Thanks guys! Should I close the issue?

**Comment by dbieber** [comment]
Excellent!
Yes, marking as closed
