### ISSUE TITLE
Use Fire with pytorch DDP

### ISSUE THREAD

**Issue by liqi17thu** [google/python-fire#323]
Hi, I want to use Fire with pytorch Distribute Data Parallel. However, when I launch the job, the torch.distributed.launch will insert a 'local_rank' arg, which seems to be taken as the commands of Fire. I am wondering how could I solve this?

![image](https://user-images.githubusercontent.com/48043983/109809847-be39d600-7c63-11eb-8f7c-78ae9d69c251.png)

**Comment by dbieber** [comment]
I've never used pytorch Distribute Data Parallel, so take my answer with a grain of salt.

It sounds like torch.distributed.launch expects a binary that accepts a flag `--local_rank`. If so, you could add `local_rank` as a keyword arg to your train method.  It's hard to say if that's the case just from your screenshot though.

**Comment by liqi17thu** [comment]
I think the problem is torch.distributed.launch will always insert `--local_rank` at the beginning of main.py, which is taken as the command I want to launch.

**Comment by dbieber** [comment]
If that's the case you could try:

```
class Launcher:
  def __init__(self, local_rank):
    self.local_rank = local_rank

  def train(self, ...
```

**Comment by liqi17thu** [comment]
This solution is elegant! Thanks a lot!
