### ISSUE TITLE
Question regarding passing arguments using fire

### ISSUE THREAD

**Issue by venkatraman07** [google/python-fire#34]
HI,
I have the following question regarding passing of arguments. Please clarify me.
I have 3 classes A B and C. Class C has a method which consumes an argument say arg3. Class A takes arg1 and arg2 as arguments. When I try to pass the 3rd argument to the class C I get an error saying "can not consume argument for that method"
example code below
a.py
-----
```
class A (object):
    def __init__(self, arg1, arg2):
         self.b = B(arg1, arg2)
         self.arg1 = arg1
         self.arg2 = arg2
def main():
  fire.Fire()
if __name__ == "__main__":
   main()
```
--------------------------------
b.py
----
```
class B():
    def __init__(self, arg1, arg2):
          self._arg1 = arg1
          self._arg2 = arg2
          self._imp = self._get_imp()
    
     def _get_imp(self):
           
           if (arg1 == arg1):
                imp = C()
           else 
                imp = D()
           return imp

     def __getattr__(self, name):
          obj = getattr(self._imp, name)
          return obj
```
----------------------------
c.py
----
```
class C():
    def create(self, arg3):
        print("argument 3 %d" %arg3

```
----------------
if I give the following command I get an error saying 'Could not consume arg', 'create'. This create is the
method in class C() which expects an argument. FYI

`python a.py B --arg1 arg1 --arg2 arg2 create 3` 

arg1 and arg2 are consumed by B and arg3 needs to be consumed by class C but for some reason I am not able to pass arg3 to create method in C.

1) How can I pass arguments to methods in classes when I call multiple classes using fire.

2) if there are no arguments for the class C method then its able to print the message.

**Comment by dbieber** [comment]
**Try this command instead**
Without modifying your code, you should be able to run this command:

`python a.py B --arg1 arg1 --arg2 arg2 _imp create 3`


**What was wrong with your command?**
Here's what is happening now when you run `python a.py B --arg1 arg1 --arg2 arg2 create 3`:

`python a.py`: runs the a.py file, where `fire.Fire()` is called. Since you pass no arguments to `Fire`, it makes everything in `a.py` available at the command line. I think you're importing `B` in `a.py`, so B is available.

`B --arg1 arg1 --arg2 arg2`: An instance of `B` is constructed with arguments `arg1` and `arg2`.

`create`: Fire then tries to use the create argument to access a member of your instance of B, which fails since B doesn't have a method named create. If instead you access the `_imp` member of B, and then call `create`, it should do what you're looking for.

**Comment by venkatraman07** [comment]
Thanks for explanation. Follow up question. if I initialize another class X and add a method in a.py like this
class A (object):
    def __init__(self, arg1, arg2):
         self.x  = X()   <----- added new initialization
         self.b = B(arg1, arg2)
         self.arg1 = arg1
         self.arg2 = arg2

     def connect(self)   <---- added new method
          some implementation code...
x.py
---
class X():   <-- how can I access or pass the arg1 arg2 .. to X()? So that the methodsin X can access those arguments
     def create()
           print("x");

if I run the following command
python a.py A --arg1 arg1 --arg2 arg2 connect 
connect will have access to all the arguments that were passed to A. Is there any way we could pass these arguments to class X?

**Comment by dbieber** [comment]
If I understand your question correctly, then one option is to pass them via `X`'s constructor, just as you do for `B`:

```
class A (object):
    def __init__(self, arg1, arg2):
         self.x = X(arg1, arg2)   # added arg1 and arg2 here
         self.b = B(arg1, arg2)
         self.arg1 = arg1
         self.arg2 = arg2

     def connect(self):
          some implementation code...
```

```
class X():   
     def __init__(self, arg1, arg2):  # methods in X can now access the arguments from A
       self.arg1 = arg1
       self.arg2 = arg2
     def create():
           print("x", self.arg1, self.arg2);
```

---------

Or if you want `X` to have even broader access to `A`'s properties, you could pass an instance of `A` itself, like this:

```
class A (object):
    def __init__(self, arg1, arg2):
         self.x = X(self)   # we give X access to an instance of A
         self.b = B(arg1, arg2)
         self.arg1 = arg1
         self.arg2 = arg2

     def connect(self):
          some implementation code...
```

```
class X():
     def __init__(self, a):
       self.a = a   # X can now access anything from a
     def create():
           print("x", self.a.arg1, self.a.arg2);   # Here's how you'd access arg1 and arg2
```
