### ISSUE TITLE
ModuleNotFoundError: No module named 'fire' 

### ISSUE THREAD

**Issue by sasha-moiseenko** [google/python-fire#340]
Hi there!
Please, help to find out why I get this issue after module's import and installation. Behind I've added some proofs (stderr from my terminal):
(venv) sasha@sasha-m-laptop:/PycharmProjects/pythonProject$ pip3 install fire
Processing /home/sasha/.cache/pip/wheels/1f/10/06/2a990ee4d73a8479fe2922445e8a876d38cfbfed052284c6a1/fire-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from fire) (1.14.0)
Requirement already satisfied: termcolor in /home/sasha/.local/lib/python3.8/site-packages (from fire) (1.1.0)
Installing collected packages: fire
Successfully installed fire-0.4.0
(venv) sasha@sasha-m-laptop:/PycharmProjects/pythonProject$ python ./venv/final_version.py
Traceback (most recent call last):
File "./venv/final_version.py", line 4, in
import fire
ModuleNotFoundError: No module named 'fire'

Part of my script with import:
import logging
import fnmatch
import subprocess
import fire
import os

def setup_log(name):
logger = logging.getLogger(name) # > set up a new name for a new logger

logger.setLevel(logging.INFO)
Also I've tried use pip for installation, but there wasn't any impact on result...

**Comment by sasha-moiseenko** [comment]
also some useful outputs:
(venv) sasha@sasha-m-laptop:~/PycharmProjects/pythonProject$ python3 ./venv/final_version.py 
Traceback (most recent call last):
  File "./venv/final_version.py", line 4, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'
(venv) sasha@sasha-m-laptop:~/PycharmProjects/pythonProject$ type python
python is hashed (/home/sasha/PycharmProjects/pythonProject/venv/bin/python)
(venv) sasha@sasha-m-laptop:~/PycharmProjects/pythonProject$ type pip3
pip3 is hashed (/usr/bin/pip3)

**Comment by beasteers** [comment]
hi not sure if you figured it out already, but you're installing using the wrong pip. 

Your python path is: `/home/sasha/PycharmProjects/pythonProject/venv/bin/python`
So your pip path should be: `/home/sasha/PycharmProjects/pythonProject/venv/bin/pip`

You're using the built-in pip `/usr/bin/pip3` so if you did `/usr/bin/python` and then ran `import fire` it should work.

With your `venv` enabled, try `which pip` and see if the path matches above. If it shows the pip inside of your virtual environment (`..../pythonProject/venv/bin/pip`), you can just do: `pip install fire`

**Comment by sasha-moiseenko** [comment]
> hi not sure if you figured it out already, but you're installing using the wrong pip.
> 
> Your python path is: `/home/sasha/PycharmProjects/pythonProject/venv/bin/python`
> So your pip path should be: `/home/sasha/PycharmProjects/pythonProject/venv/bin/pip`
> 
> You're using the built-in pip `/usr/bin/pip3` so if you did `/usr/bin/python` and then ran `import fire` it should work.
> 
> With your `venv` enabled, try `which pip` and see if the path matches above. If it shows the pip inside of your virtual environment (`..../pythonProject/venv/bin/pip`), you can just do: `pip install fire`

Hi) I’ve already got it, my fault) thanks for reply

**Comment by d3lt4ls0** [comment]
##hello !! i am facing this issue can any one solve my issue ..?

python3 oneforall.py --target example.com run
Traceback (most recent call last):
  File "/home/d3lt4ls/Desktop/OneForAll/oneforall.py", line 15, in <module>
    import export
  File "/home/d3lt4ls/Desktop/OneForAll/export.py", line 13, in <module>
    from common import utils
  File "/home/d3lt4ls/Desktop/OneForAll/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/home/d3lt4ls/Desktop/OneForAll/common/database.py", line 8, in <module>
    from config.log import logger
  File "/home/d3lt4ls/Desktop/OneForAll/config/log.py", line 38, in <module>
    logger.add(log_path, level='DEBUG', format=logfile_fmt, enqueue=True, encoding='utf-8')
  File "/home/d3lt4ls/.local/lib/python3.11/site-packages/loguru/_logger.py", line 762, in add
    wrapped_sink = FileSink(path, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3lt4ls/.local/lib/python3.11/site-packages/loguru/_file_sink.py", line 166, in __init__
    self._initialize_file()
  File "/home/d3lt4ls/.local/lib/python3.11/site-packages/loguru/_file_sink.py", line 185, in _initialize_file
    path = self._prepare_new_path()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3lt4ls/.local/lib/python3.11/site-packages/loguru/_file_sink.py", line 181, in _prepare_new_path
    os.makedirs(dirname, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/d3lt4ls/Desktop/OneForAll/results'
