### ISSUE TITLE
Passing function as an argument

### ISSUE THREAD

**Issue by tory1103** [google/python-fire#349]
Hello, can i pass some functions to fire?, like lambda or other predefined?

For example:

```python
from fire import Fire

dictionary = {"key":"value"}
Fire()
```
```python
>>> py file.py dictionary get lambda: list(dictionary.keys())[-1]
"value"
```

This cli passes a lambda function as an argument, is this possible using fire?

**Comment by dbieber** [comment]
No, that is not possible using fire.

Have a look at [pypyp](https://github.com/hauntsaninja/pyp) -- you might be interested in that project too!
