### ISSUE TITLE
Output help as markdown

### ISSUE THREAD

**Issue by bovlb** [google/python-fire#352]
Thanks for a useful tool.  Would it be possible to generate the help output as markdown text, suitable for saving to github repos?

**Comment by prithvijitguha** [comment]
Hey everyone! Is anyone working on this. I'd like to help out. I'm new to open source. 

Thank you in advance!

**Comment by dbieber** [comment]
Neat idea. I don't know if it would make sense to include this in fire. I see the value, but I think it's outside the scope of what we want fire to do. I'd certainly be interested to see it in action if one of you does build this feature though!
