### ISSUE TITLE
Documentation should cover adding descriptions for positional arguments and flags

### ISSUE THREAD

**Issue by Mastermjr** [google/python-fire#357]
This is from my coworker, so I can't take credit, but I want to document this for others who experience a similar frustration or issue. 

## Expectation: 
I can add descriptions to parameters that I add under the "arguments" keyword in the docstring. 
```python
def function(param1, param2=False):
    """
    this function does things
    
    Arguments: 
       param1=None : my definition for what param1 does
       param2=False : my definition for what param2 does
    """
```
then I should run `python3 script.py --help`
and see: 
```
NAME
    script.py -  this function does things

SYNOPSIS
    script.py  <flags>

DESCRIPTION
       Arguments: 
       param1=None : my definition for what param1 does
       param2=False : my definition for what param2 does
 
NOTES
    You can also use flags syntax for POSITIONAL ARGUMENTS
(END)
```

## actual result:
however I actually get: 
```
NAME
    __main__.py - this thing does things

SYNOPSIS
    __main__.py DOMAIN_CONF <flags>

DESCRIPTION
    this function does things
    
FLAGS:
       --param1=PARAM1
        Default: None
    --param2=PARAM2
        Default: False

NOTES
    You can also use flags syntax for POSITIONAL ARGUMENTS
```

# Solution: 
Make sure you start the doc strings like this and everything will be fine: 
```python
def function(param1, param2=False):
    """
    this function does things
    
    Positional Arguments: 
       param1=None : my definition for what param1 does
       param2=False : my definition for what param2 does

    Flags:
       flag1=False :  this is a flag
       
     Notes:
       extra info you want to add here
    """
```

You can also follow the titles from the normal `--help` flag and then you can add those titles to your docstrings and they will print out in the appropriate place. For example adding a `Notes:` into the docstrings will cause a `Notes:` to appear in the description. 

I'm honestly not sure this "bug" will be fixed or if its a "feature", but I'm documenting this here for my future self and others that have had the same issue

**Comment by dbieber** [comment]
Thanks for writing this up.

Fire's documentation extraction is best effort and aims to support the most common docstring formats, but it's imperfect and doesn't work with every format someone might use.

I'm going to close this issue for now, but feel free to open additional issues/PRs either with improvements to the docstring parser or with changes to the fire documentation.
