### ISSUE TITLE
Is there something that does the opposite with command line python applications?

### ISSUE THREAD

**Issue by joeld1** [google/python-fire#370]
Hello, this project is pretty nifty!

I was just reaching out because I was wondering if anyone here knows of any Python libraries that do the opposite of python-fire (python CLI-only-app -> python class/object)?

Thank you!

**Comment by garryspins** [comment]
what would be the use case of this?

**Comment by dbieber** [comment]
I'm not aware of such a project.
It's a cool idea -- any ideas how a project like that might work?
