### ISSUE TITLE
Classes as parameters

### ISSUE THREAD

**Issue by pbarker** [google/python-fire#374]
Classes as parameters should be expanded and added to the argument set.

```python
@dataclass
class Foo():
    a: str = "hello"
    b: str = "world"

def bar(foo: Foo, c: str = "hello"):
    # something
```

Currently the help will display as:
```
Usage: baz.py FOO <flags>
  optional flags:        --c 
```
Ideally the class would be expanded:
```
Usage: baz.py <flags>
  optional flags:        --c  |  --foo.a  |  --foo.b 
```

**Comment by dbieber** [comment]
Thanks for the suggestion. We don't have plans to add this at this time, but I do see the value and think something like this could be a good addition. See also #384 for a similar related suggestion.
