### ISSUE TITLE
Changing the value of a variable in a script

### ISSUE THREAD

**Issue by ma-sadeghi** [google/python-fire#375]
Many thanks for creating this great package!

I have a simple script (no functions) like the one below:

```python
x = 1  # default value of x

# do something with x
```

I want to be able to change the value of `x` from CLI without having to wrap the code in a function. I have figured that the following (workaround) works:

```python
import fire

x = fire.Fire(lambda r=1: r)

# do something with x
```

Is this considered the preferred solution or is there a better way? Thanks!

**Comment by dbieber** [comment]
I recommend writing a function

```
import fire

def fn_name(x=1):
  # do something with x
  ...

fire.Fire(fn_name)
```

Then when you run your code it will run with x == 1 by default, and you can also set the value of x using e.g. --x=5 at the command line.
