### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name' when installing python 3.7

### ISSUE THREAD

**Issue by GitBib** [google/python-fire#407]
When tests are run using python-fire, an error occurs.
Example error: https://app.travis-ci.com/github/GitBib/pyasstosrt/jobs/583684057

**Comment by dbieber** [comment]
Unfortunately the example error is no longer visible on Travis. Going to close the issue as I assume being 1.5 years old it's not blocking you anymore, but feel free to reopen with new logs if still relevant.
