### ISSUE TITLE
New Release v0.5.0

### ISSUE THREAD

**Issue by Ashton-Sidhu** [google/python-fire#409]
Hi,

Thanks for creating and maintaining Python-Fire, I'm just wondering if there's any plans to publish another release to Pypi or should we installing from main? The new `serialize` parameter would be really helpful for our use cases !

**Comment by mwort** [comment]
I second that. @dbieber thanks for all your efforts in building Fire 🔥 Lots of good PRs and issues dont get merged and the last release is from Jan 2021, suggesting that you probably dont have much time for this anymore. I wondered if there is scope to:
- a) either invite more core maintainers to allow them to take care of PRs and releasing (I'm guessing that will be restricted by google's policy) or
- b) move this to a dedicated python-fire organisation where more maintainers can be invited and we are not bound by Google CLAs anymore (which seemse to have stalled some PRs).

I fear if PRs pile up and no new releases are made, ppl (me included) will be detered from using Fire long-term.

**Comment by dbieber** [comment]
A draft of the release is ready. I'll likely do the release early next week (as opposed to now, Friday evening) so that I'll be around in case I need to fight any fires. 🔥

**Comment by mwort** [comment]
Thanks @dbieber , looking forward to the release!

**Comment by dbieber** [comment]
Live on pypi now.

`pip install -U fire` to upgrade.

Thanks for your patience, all.
