### ISSUE TITLE
Defaults for kwonly arguments don't show in help

### ISSUE THREAD

**Issue by melsabagh-kw** [google/python-fire#410]
Fire (v0.4.0, master) does not seem to show default values for keyword-only arguments. Consider the following example:

```python
#!/usr/bin/env python3

import fire


def foo(*, bar=True):
    print(bar)


if __name__ == '__main__':
    fire.Fire(foo)
```

Save it as `foo.py` and run `python3 foo.py --help`.

### Expected Output:

```shell
INFO: Showing help with the command 'foo.py -- --help'.

NAME
    foo.py

SYNOPSIS
    foo.py <flags>

FLAGS
    --bar=BAR
        Default: True
```

### Actual Output:

```shell
INFO: Showing help with the command 'foo.py -- --help'.

NAME
    foo.py

SYNOPSIS
    foo.py <flags>

FLAGS
    --bar=BAR
```

Looks like a one line change could fix this: change the `return` statement here https://github.com/google/python-fire/blob/37c4305194ff3d0a63f435f08a40e14b1978bd4e/fire/helptext.py#L527 to:

```python
    return repr(spec.kwonlydefaults.get(flag, ''))
```

**Comment by amrutha1098** [comment]
Hi I would like to work on this issue.

Thanks!
