### ISSUE TITLE
Make alias for arguments

### ISSUE THREAD

**Issue by LicharYuan** [google/python-fire#429]
Hi, can `fire` set arguments like  `-u`, `--username` in argparser? 
For example: 

```python
    parser.add_argument(
        "-u", "--username",
        type=str,
        default=None)
```

**Comment by dbieber** [comment]
This is not a planned feature. We do support short flags though, e.g. -u for --username if its the only arg starting with u.

I'm interested to know what syntax you would suggest for an alias feature.

**Comment by LicharYuan** [comment]
Thanks for your reply :).  

In my example, the name of some arguments is too long.  Alias will make command lines more simple. 
Of course,   I can shorten these arguments.  But for  API consistency, I cannot changes their names arbitrarily. That's why i want alias these in command line. 

The short flag is good!  And enough for my case.
