### ISSUE TITLE
Remove deprecated pipes dependency

### ISSUE THREAD

**Issue by schlomo** [google/python-fire#444]
I get this warning:

```
.venv/lib/python3.11/site-packages/fire/core.py:59
DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
    import pipes
```

Can you please remove pipes? See https://docs.python.org/3/library/pipes.html#:~:text=Deprecated%20since%20version%203.11%2C%20will%20be%20removed%20in%20version%203.13%3A%20The%20pipes%20module%20is%20deprecated%20(see%20PEP%20594%20for%20details).%20Please%20use%20the%20subprocess%20module%20instead. for more infos.

Fire actually only uses the `quote()` function and according to https://github.com/python/cpython/blob/3.11/Lib/pipes.py#L66 this is imported from `shlex` so it should be a straight-forward replacement.

**Comment by a-detiste** [comment]
It's fixed
