### ISSUE TITLE
[Question] Even if no type hints is supplied, would `python-fire` accept stub files?

### ISSUE THREAD

**Issue by Diogo-Rossi** [google/python-fire#456]
I know there is a guide line of code style [remarking it will not accept type hints](https://github.com/google/python-fire/blob/master/CONTRIBUTING.md#:~:text=No%20type%20hints%2C%20as%20described%20in%20PEP%20484%2C%20to%20maintain%20compatibility%20with%20Python%20versions%20%3C%203.5.).

However, would you accept type hints in [stub files](https://mypy.readthedocs.io/en/stable/stubs.html#:~:text=A%20stub%20file%20is%20a,and%20most%20importantly%2C%20their%20types.), rather than in source files?

**Comment by dbieber** [comment]
The upcoming release v0.6.0 will be the last release to support Python 2. After that, we will drop Python 2 support and type hints will be fair game.
