### ISSUE TITLE
guide sample code is entered incorrectly

### ISSUE THREAD

**Issue by fuhaha** [google/python-fire#466]
hi
guide sample code is wrong
https://github.com/google/python-fire/blob/master/docs/guide.md#accessing-properties
sample code

self.name = dict(airports).get(self.code)
to 
self.name = dict(airports.airports).get(self.code)

**Comment by Adityakhalkar** [comment]
As its a `from airports import airports` import , we do not need to call airports module for referencing the `airports` member.

**Comment by fuhaha** [comment]
my mistake 
In my code, airports.py was in the airports directory.
If airports.py is in the same directory, you should be fine.
