### ISSUE TITLE
Remove test requirement on mock

### ISSUE THREAD

**Issue by dvzrv** [google/python-fire#469]
Hi! I package this project for Arch Linux.

We are currently trying to finally get rid off mock as test requirement (as it is included with Python since 3.3).
It would be great if the test requirement on mock in this project could be replaced by the internal unittest.mock.

Related: This project seems to support Python versions that are no longer supported by the Python project itself (see https://www.python.org/downloads/). Is there a reason for that?

**Comment by dbieber** [comment]
The upcoming release v0.6.0 will be the last release to support Python 2. After that, we'll drop support for Python 2. We can easily drop the dependency on mock at that time.

**Comment by dvzrv** [comment]
@dbieber thanks, that's great to hear.

Are you able to give a rough ETA on v0.6.0 and a follow-up release? :)

**Comment by dbieber** [comment]
v0.6.0 we put out today. I don't have an estimate for the follow-up yet unfortunately.

**Comment by dvzrv** [comment]
Thanks! I can carry a patch for the mock removal until then.

**Comment by dbieber** [comment]
We have (finally 😅) removed the dependency on mock from the codebase https://github.com/google/python-fire/pull/545
(but have not yet released with the dependency removed).

**Comment by dbieber** [comment]
@dvzrv At last, 0.7.0 is released. Thank you for your patience.
