### ISSUE TITLE
How to set the number of args at least one?

### ISSUE THREAD

**Issue by anemele** [google/python-fire#475]
Hi.

I have a function as follow

```python
def f(*file):
    pass
```

and use `argparse` to create cli

```python
parser.add_argument('file', nargs='+', type=str)
```

It needs at least one argument, given no argument will return

```
usage: xxx [-h] file [file ...]
```

I want migrate to `fire` but `fire` doesn't perform as expected, it returns

```
xxx [FILE]..
```

So, I wonder is there any method to set the number of args?

**Comment by dbieber** [comment]
To write a Python function that takes at least one arg, have a single required positional arg followed by varargs. E.g.

```python
def f(required, *optional):
  all_args = [required] + optional
```

While you can't get precisely the behavior you want ("file, [file ...]"), you can get close with:


```python
def f(file, *files):
  files = [file] + files
```
