### ISSUE TITLE
FEATURE: key:value parsing in arguments

### ISSUE THREAD

**Issue by itsmeadarsh2008** [google/python-fire#518]
For example
```sh
python foo.py key:value
# Splits into key and value

python foo.py gh:itsmeadarsh2008/flpc
# gh argument passed with "itsmeadarsh2008/flpc"
```

**Comment by dbieber** [comment]
This is an interesting idea.
The syntax today for setting arguments is `python foo.py --key=value` or `python foo.py --gh=itsmeadarsh2008/flpc`.
We don't have any plans for supporting the : syntax going forward.
