### ISSUE TITLE
Can the official documentation be updated with the latest support

### ISSUE THREAD

**Issue by wssf812** [google/python-fire#538]
I see that asyncio is already supported in version 0.4.0, but there seems to be no relevant introduction in the documentation, and only normal functions, classes, etc. are included in the relevant examples. Unless the relevant fix is found in the issue or checked in the source code, is not can be discovered whether coroutines are supported. Can we add support for coroutines starting from 0.4.0 and related examples in the document, such as:

def a():  and async def a(): 
This feeling is quite clear。This is just a suggestion. Looking forward to your reply！

**Comment by dbieber** [comment]
Sure thing.
Please have a look here and provide feedback if you have any https://github.com/google/python-fire/pull/553
