### ISSUE TITLE
Establish a comms channel for contributors

### ISSUE THREAD

**Issue by dbieber** [google/python-fire#61]
This ticket is for discussing + establishing a comms channel for contributors.

Perhaps [Gitter](https://gitter.im/google/python-fire) is the best way to do this.
@saurabhkpatel suggested Slack, but with Slack you need to specify a list of domains from which to allow email addresses, whereas I want anyone to be able to join the conversation. There are ways around this like [slackin](https://github.com/rauchg/slackin), but at a glance it looks like I'd have to commit to maintaining a server running slackin indefinitely for this to be a viable workaround, which I'm not prepared to do.

+@jtratner @nealmcb @saurabhkpatel @jgarst @keatinge @r0fls as an FYI.

**Comment by r0fls** [comment]
gitter works great for another project i work on. I've heard slack can be bad for OS for various reasons.

**Comment by nealmcb** [comment]
I was just going to look to see if fire had a gitter :)
I use both slack and gitter.  Gitter seems right for this - good integration, a fine tool.

**Comment by saurabhkpatel** [comment]
Let's start with Gitter for now, as everybody prefers Gitter. :)

**Comment by dbieber** [comment]
The gitter's at https://gitter.im/google/python-fire.

We'll want to add this to contributing.md and add a "Community" section to the readme/Guide.

Related musing: maybe the Guide should become the readme... and we should probably set up a readthedocs...

**Comment by ibocon** [comment]
Thanks to open comms channel.
