### ISSUE TITLE
python2.7 ipython fails to install

### ISSUE THREAD

**Issue by jmunsch** [google/python-fire#63]
The ipython dependency fails to install with `ipython<6.0` using python 2.7.13 as part of setup.py `install_requires`

I understand the reasoning for not wanting to maintain backports

I was able to use `ipython==5.3` with success.

by using/installing python-fire with the dist tar.gz from `python setup.py sdist` of the master branch on git.

**Comment by dbieber** [comment]
Thanks for opening the issue. See also #57.

What did you do when it failed, `pip install fire`? The version currently in pypi has the dependency listed as `ipython`, whereas master lists the dependency as `ipython<6.0`. So what's currently on master should work w/ python 2.7.

It sounds like a better way to do this going forward is:
https://github.com/ipython/ipython/issues/10329#issuecomment-293294424
```python
if sys.version_info[0] < 3 and 'bdist_wheel' not in sys.argv:
    install_req.remove('ipython')
    install_req.append('ipython<6')
```

**Comment by jmunsch** [comment]
Inside a custom package named `swiftutils` I have:

```
install_requires=['fire']
```

Then in some other packages I have something like this in setup.py on a simple pypi server:

```
install_requires=['swiftutils'],
dependency_links=['http://jenbuild-5462.xxx.com/simple/swiftutils/'],
```

I then do a `python setup.py install` with these other packages.

This looks like a similar issue as the ones you linked. 

The `dependency_links` of setuptools uses pypi/pip? 

Thanks for the pointers, and the awesome cli utility.

I'm going to close this issue, as it looks like a duplicate.
