### ISSUE TITLE
Clearly document what python versions are supported (ie, python 3 support?)

### ISSUE THREAD

**Issue by jeffwidman** [google/python-fire#69]
Not seeing anything on the readme. Perhaps add [shields.io](https://shields.io) badges that are automatically generated from the pypi listing?

**Comment by dbieber** [comment]
Showing this clearly is a good idea.
For what it's worth, the supported Python versions are 2.7, 3.4, 3.5, and 3.6

**Comment by jeffwidman** [comment]
I'll submit a PR next week after pycon

**Comment by ajomadlabs** [comment]
Can I take up this issue ?

**Comment by dbieber** [comment]
Sure thing.

**Comment by ajomadlabs** [comment]
@dbieber Can you assign me this issue

**Comment by jeffwidman** [comment]
No need for that, just submit a pull request trying to solve it...

**Comment by ajomadlabs** [comment]
@dbieber @jeffwidman I should add the supported versions of python and add the shields.io badge. Correct me if I am wrong

**Comment by dbieber** [comment]
Thanks for doing this @ajomadlabs.
