### ISSUE TITLE
Outdated PyPi version

### ISSUE THREAD

**Issue by TheCraftKid** [google/python-fire#72]
It appears installing the fire module using pip produces an [outdated version](https://pypi.python.org/pypi/fire/0.1.0) of the library. I've run into an error identical to #6, and after checking the result of that, it appears the update that fixed #6 can only be installed by cloning the repository and running setup.py, as suggested.

FYI, I was using fire version 0.1.0 with Python 3.5.2 when installed using pip.

**Comment by dbieber** [comment]
Yes we were overdue for a release.
I've gone ahead and updated PyPi. The release notes are [here](https://github.com/google/python-fire/releases/tag/v0.1.1).
