### ISSUE TITLE
Non-zero exit codes

### ISSUE THREAD

**Issue by gerardlouw** [google/python-fire#73]
I'd like a way to make my CLI exit with a custom, non-zero code when using Python-fire.

One option might be to have a specific value you could return from your Fire function in order to exit with a particular code. This could be accomplished with, say, a simple ExitCode class wrapping an integer.

Possibly a better idea is to have a special exception class, e.g. ExitCodeError, such that raising an instance of a that class (or a subclass thereof), modifies the exit code of the CLI.

**Comment by jtratner** [comment]
Could you raise SystemExit in your function?  That should cause the CLI to
exit with the exit code you want?

**Comment by dbieber** [comment]
Using `sys.exit(number)` from within your code should cause Fire to exit with `number` as it's exit code.

(We also have the "FireExit" class, which you could raise with a custom exit code, but FireExit is considered an implementation detail and you shouldn't rely on it atm.)

**Comment by gerardlouw** [comment]
Perfect - @jtratner's suggestion does exactly what I was looking for. I wasn't aware of this feature of Python.

As an aside, the reason for wanting to throw an exception rather than using `system.exit`, is so that the same code can be used both as a CLI and programmatically (where in the latter case one might wish to handle the exception rather than exit).

**Comment by dbieber** [comment]
Glad it worked!

Did you know `sys.exit(n)` and `raise SystemExit(n)` are actually [equivalent](https://github.com/python/cpython/blob/master/Python/sysmodule.c#L255)?
So when someone does sys.exit(0) you can prevent Python from exiting by catching the SystemExit exception.
