### ISSUE TITLE
How to successfuly parse list of string ip address?

### ISSUE THREAD

**Issue by tongorz** [google/python-fire#79]
--args [a,b] can be parsed into list of string correctly.
--args [192.168.1.1,192.168.1.2] is parsed to string.
I also tried '[192.168.1.1, 192.168.1.2]', '["192.168.1.1","192.168.1.2"]', all failed

Thank you

**Comment by dbieber** [comment]
Your final attempt should work.

With this program:
```
import fire

def check(x):
 return [x, type(x)]

fire.Fire(check)
```

Running this command:
`example '["192.168.1.1","192.168.1.2"]'`

Gives this output:
```
["192.168.1.1", "192.168.1.2"]
<class 'list'>
```

The reason you have to be so careful is that bash parses your input before Fire gets a chance to see it, so you must quote your input in order for the quotation marks to be available in the arg that Fire sees.

**Comment by tongorz** [comment]
@dbieber 
Maybe the reason is that I use Windows. 
I run your code both in cmd and powershell, the output is still string.

`C:\somepath>python test.py '["192.168.1.1","192.168.1.2"]'
[192.168.1.1,192.168.1.2]
<class 'str'>`

**Comment by jtratner** [comment]
Did you try:

```
C:\somepath>python test.py ["192.168.1.1","192.168.1.2"]
```

Perhaps in powershell you don't need the outer level of quoting in the same way.

**Comment by tongorz** [comment]
@jtratner 
`C:\somepath>python test.py ["192.168.1.1","192.168.1.2"]` will be parsed into string too.

**Comment by dbieber** [comment]
> I run your code both in cmd and powershell, the output is still string. C:\somepath>python test.py '["192.168.1.1","192.168.1.2"]' [192.168.1.1,192.168.1.2] <class 'str'>

It's interesting that both the outer and inner quotes are being stripped by powershell. I don't know why that would be. In powershell, you can try putting a backtick (`) in front of each of the inner quotes, but based on the quoting rules here (https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_quoting_rules) it doesn't look like it should be necessary. I don't have a windows machine handy atm or else I would try this myself.

**Comment by tongorz** [comment]
@dbieber 
```
PS C:\Users\Tong\Dropbox\DOC\Python\Junos_Auto\port_config> python test_fire.py '[\"192.168.1.1\",\"192.168.1.2\",\"
192.168.1.3\"]'
["192.168.1.1", "192.168.1.2", "192.168.1.3"]
<class 'list'>
```
This Way Work！

**Comment by dbieber** [comment]
> Will python-fire improve this part?

It's unlikely this will change soon. That said, I'm surprised that you needed to escape those inner quotes -- I'll need to look at this more when I have access to windows because I want to understand why `'["192.168.1.1","192.168.1.2"]'` didn't work.
