### ISSUE TITLE
New Release (v0.1.2)

### ISSUE THREAD

**Issue by CJ-Wright** [google/python-fire#80]
Would it be possible to get a new release (now that iypthon is not a dep?)

**Comment by dbieber** [comment]
I was hoping we'd have #77 done before the release to minimize the difference in experience for users w/ + w/o ipython. Should be fine to release without it though; I'll take a closer look on ~Monday.

**Comment by CJ-Wright** [comment]
This just changed some of the packaging details, now that the package is made it is not as pressing.

**Comment by micahjsmith** [comment]
+1 to provide a new release if possible, given that the current packaged version (0.1.1) forces downgrade of ipython to <0.6.

**Comment by dbieber** [comment]
The release v0.1.2 is now on PyPi. Thanks for your patience.
Release notes are at https://github.com/google/python-fire/releases/tag/v0.1.2
