### ISSUE TITLE
All possible usages are printed out when an object was returned

### ISSUE THREAD

**Issue by k4ml** [google/python-fire#83]
For example:-

```
class Stuff(object):
    def do_this(self):
        pass
    
    ... many more methods

def testx():
    return Stuff()

def main():
    fire.Fire({
        'testx': testx,
    })
```
And when executed, all the methods from the returned object was printed out:-

```
Type:        Stuff
String form: <Stuff object at 0x7f43202a1be0>
File:        ~/xxx/cli.py

Usage:       cli testx
             cli testx do-this
```
This mean the real output from the command no longer helpful as it way far to the top of the console (you have to scroll up to see the command real output). There must be a way to disable printing out the returned value as that the least concern from cli tools.

**Comment by shippy** [comment]
+1. 

Quick workaround 1: add `- __str__` or equivalent after the CLI command, taking advantage of Fire's ability to call any further methods of the returned objects.

Quick workaround 2:

```python
def testx_cli(**kwargs):
    return testx(**kwargs).__str__

def main():
    fire.Fire({
        'testx': testx_cli,
    })
```

Both of these are PITA and I wish that there was either a way to specify the output post-processing, or that Fire would recognize when it's being piped not into another Fire command but into stdout and used `__str__` on its own.

**Comment by dbieber** [comment]
Starting in v0.2.0 Fire now uses `__str__` on its own if a custom `__str__` function has been defined. Overall the default output has been greatly improved in this release. Hopefully this resolves both of your pain points.

The release should be going out later today (July 26 2019).
