### ISSUE TITLE
 Receive date parameter conversion confusion[Receive Operation not String]

### ISSUE THREAD

**Issue by shaozhipeng** [google/python-fire#86]
import fire
class Test:
    def __init__(self):
        print('初始化成功')

    def stat(self, daystr='1970-01-01'):
        print('开始--%s' % daystr)

if __name__ == '__main__':
    fire.Fire(Test)

命令行测试并输出结果：
$ python3 tests.py stat 2016-12-10
初始化成功
开始--1994
$ python3 tests.py stat 2016-12-09
初始化成功
开始--2016-12-09
$ python3 tests.py stat 2017-01-09
初始化成功
开始--2017-01-09
$ python3 tests.py stat 2016/12/10
初始化成功
开始--2016/12/10
$ python3 tests.py stat xxx
初始化成功
开始--xxx
$ python3 tests.py stat 中文
初始化成功
开始--中文
$ python3 tests.py stat 2017-12-10
初始化成功
开始--1995
$ python3 tests.py stat 2017-12-11
初始化成功
开始--1994
$ python3 tests.py stat 2017-12-12
初始化成功
开始--1993
$ python3 tests.py stat 2016-12-12
初始化成功
开始--1992
$ python3 tests.py stat 1995-10-10
初始化成功
开始--1975
$ python3 tests.py stat 1995-11-10
初始化成功
开始--1974

**Comment by shaozhipeng** [comment]
When month >= 10 then the result is year minus month and minus day

**Comment by shaozhipeng** [comment]
issue resoved '"1995-11-10"'

**Comment by shaozhipeng** [comment]
got it
$ python example.py 10
int
$ python example.py "10"
int
$ python example.py '"10"'
str
$ python example.py "'10'"
str
$ python example.py \"10\"
str

**Comment by dbieber** [comment]
I'm glad you were able to answer your own question :)
