### ISSUE TITLE
Wrong value is passed when variable name is in quotes

### ISSUE THREAD

**Issue by feinsteinben** [google/python-fire#90]
consider the following code:
```python
# file: bug.py

from __future__ import print_function
import fire

def main(x):
    print(x)

if __name__ == '__main__':
    fire.Fire(main)
```

when running `python bug.py "--x=abc"` it prints `abc` (I'd expect `--x=abc`). **I think it's a bug**.
when running `python bug.py "--x abc"` it prints `--x abc` as expected.

**Comment by dbieber** [comment]
Unfortunately your shell strips away the quotes when preparing the args list for your Python program, so there is no way for your Python program to distinguish between `--x=abc` and `"--x=abc"`.

The args list your Python program receives in the in the former case is `['bug.py', '--x=abc']`.
In the latter case it's `['bug.py', '--x abc']`.
If instead you had done `python bug.py --x abc` then the args list would be `['bug.py', '--x', 'abc']`.

If you want to pass the string "--x=abc" then you can either add a layer of quotes (`python bug.py '"--x=abc"'`) or add "--x" (`python bug.py --x=--x=abc`).

**Comment by feinsteinben** [comment]
thanks!
